const experience = document.createElement('section');
experience.className='section youtube-section';experience.id='youtube';
experience.innerHTML=`<p class="eyebrow">KEUKEN AONIKENK · SESIONES EN VIVO</p><div class="section-heading"><h1>La música de Keuken.<br>Más allá del salón.</h1><p>Dos cámaras, el sonido de la consola y una operación preparada para compartir cada recital en YouTube.<br><a class="landing-link" href="#idea">Conocé la propuesta ↓</a></p></div><p class="yt-disclaimer">Así podría vivirse un recital online. Vista ilustrativa con reacciones y audiencia ficticias.</p>
<div class="yt-shell"><div class="yt-topbar"><div class="yt-wordmark"><span class="yt-logo" aria-hidden="true">▶</span>YouTube<sup>AR</sup></div><span class="yt-search">Keuken Aonikenk en vivo <span aria-hidden="true">⌕</span></span><span class="yt-avatar">K</span></div><div class="yt-layout"><div class="yt-main"><div class="yt-player"><img src="assets/salon-show.webp" alt="Foto de un recital en Keuken presentada como portada de un reproductor ilustrativo"><span class="yt-live">● EN VIVO <small>DEMO</small></span><div class="yt-video-title">KEUKEN<br><span>SESIONES EN VIVO</span></div><div class="yt-floating" aria-hidden="true"><span>❤️</span><span>🔥</span><span>👏</span><span>💙</span><span>😍</span><span>🎶</span></div><div class="yt-player-controls" aria-hidden="true"><div class="yt-progress"></div><span>▶ &nbsp; 🔊 &nbsp; 34:28</span><span>EN VIVO &nbsp; ⚙ &nbsp; ⛶</span></div></div><h3 class="yt-title">Keuken en vivo · Música desde Lago Puelo 🎶</h3><div class="yt-channel"><img src="assets/logo.jpg" alt=""><div><strong>Keuken Aonikenk</strong><small>Centro cultural · Lago Puelo</small></div><a href="https://www.youtube.com/channel/UCTXaSLfvCtCCcbMyMckh44A" target="_blank" rel="noopener noreferrer">Canal de Keuken ↗</a></div><div class="yt-actions"><button id="yt-like" aria-pressed="false">👍 <span>12.400</span><span class="yt-like-divider">│ 👎</span></button><button id="yt-heart">❤️ Mandar amor</button><span class="yt-views">3.284 mirando ahora</span></div><p class="yt-description"><strong>La Patagonia suena y el mundo escucha. 💙</strong><br>Un escenario pequeño. Un encuentro enorme. Gracias por acompañar la música independiente. 🌎🎸✨</p></div><aside class="yt-chat"><div class="yt-chat-header"><strong>Chat destacado</strong><span>⌄ &nbsp; ⋮</span></div><div class="yt-chat-messages"><p><i class="av1">L</i><span><b>Luna</b> Qué hermoso lugar 💙💙💙</span></p><p><i class="av2">T</i><span><b>Tomi</b> Vamos Keuken!!! 🔥🔥🔥</span></p><p><i class="av3">M</i><span><b>Mar</b> Desde el sur con amor ❤️🏔️</span></p><p><i class="av4">J</i><span><b>Juli</b> Ese sonidooo 🎸👏👏👏</span></p><p class="yt-chat-highlight"><i class="av1">K</i><span><b>Keuken Aonikenk</b> Gracias por estar del otro lado ❤️</span></p><p><i class="av2">S</i><span><b>Sol</b> Me quedo todo el recital 😍🎶</span></p><p><i class="av3">N</i><span><b>Nico</b> Aguante la música en vivo 🙌🔥</span></p><p><i class="av4">V</i><span><b>Vale</b> ❤️❤️❤️❤️❤️❤️</span></p><p><i class="av1">F</i><span><b>Fran</b> Otra más!! 👏👏👏✨</span></p></div><div class="yt-chat-footer"><span aria-hidden="true">❤️ 💙 🔥 👏 😍 🎶 🙌</span><small id="yt-feedback" aria-live="polite">El encuentro también sigue del otro lado.</small></div></aside></div></div>`;
document.querySelector('#inicio').prepend(experience);
const like=document.querySelector('#yt-like');like.addEventListener('click',()=>{const liked=like.getAttribute('aria-pressed')!=='true';like.setAttribute('aria-pressed',String(liked));like.querySelector('span').textContent=liked?'12.401':'12.400';document.querySelector('#yt-feedback').textContent=liked?'¡Tu like se suma a esta demo! 💙':'Like retirado de esta demo.'});
let heartCount=0;document.querySelector('#yt-heart').addEventListener('click',()=>{heartCount++;document.querySelector('#yt-feedback').textContent=`${heartCount} ${heartCount===1?'corazón enviado':'corazones enviados'} en esta demo ❤️`;const heart=document.createElement('span');heart.className='yt-burst';heart.textContent='❤️';document.querySelector('.yt-player').append(heart);setTimeout(()=>heart.remove(),2200)});


const floorplan=document.createElement('div');floorplan.className='floorplan-block';floorplan.id='plano';
floorplan.innerHTML=`<div class="plan-intro"><h3>Dos posiciones.<br>Una sola operación.</h3><p>La toma principal busca el escenario entre las columnas. La segunda se acerca a las voces y los instrumentos. El control queda junto al sonidista.</p></div>
<div class="plan-tabs" role="group" aria-label="Capas del plano"><button data-plan="views" aria-pressed="true">Las tomas</button><button data-plan="cables" aria-pressed="false">Las conexiones</button></div>
<div class="plan-sheet" data-layer="views"><div class="plan-sheet-head"><strong>KEUKEN AONIKENK <span>/ SALÓN</span></strong><span>SALA 6 × 10 m · ESQUEMA PROPUESTO</span></div><div class="plan-scroll"><svg class="architect-plan" viewBox="0 0 1100 690" role="img" aria-labelledby="fp-title fp-desc"><title id="fp-title">Plano del salón y propuesta audiovisual</title><desc id="fp-desc">Escenario sobre la pared superior, dos columnas en su frente, acceso inferior izquierdo y acceso superior derecho según interpretación del croquis. Consola inferior derecha. Cámara uno frente al escenario; cámara dos cercana al borde derecho del escenario. La capa de conexión muestra USB por el perímetro y audio corto desde consola a computadora. Medidas aproximadas aportadas; dibujo general sin escala.</desc>
<defs><pattern id="draft-grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#dfddd4" stroke-width=".5"/></pattern><pattern id="stage-hatch" width="14" height="14" patternUnits="userSpaceOnUse"><path d="M0 14L14 0" stroke="#d2bca4" stroke-width=".8"/></pattern><marker id="blue-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#246fa9"/></marker><marker id="orange-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#b66027"/></marker></defs>
<rect width="1100" height="690" fill="#f9f7ef"/><rect x="65" y="80" width="960" height="515" fill="url(#draft-grid)"/>
<path d="M115 555V105H965V185 M965 250V555H300 M205 555H115" fill="none" stroke="#152f3b" stroke-width="10" stroke-linecap="square"/>
<path d="M300 110H715L697 158L673 196L657 240Q640 276 609 290Q493 345 389 278L365 239L345 189L320 156Z" fill="#ead8c2" stroke="#9b7b57" stroke-width="2"/>
<path d="M300 110H715L697 158L673 196L657 240Q640 276 609 290Q493 345 389 278L365 239L345 189L320 156Z" fill="url(#stage-hatch)"/>
<text x="500" y="162" class="fp-title">ESCENARIO</text><text x="500" y="187" class="fp-small">≈ 4 m de frente × 2 m de fondo</text>
<g class="plan-views"><path d="M493 534L397 205L592 205Z" fill="#3c91cf" opacity=".15"/><path d="M684 331L474 175L613 175Z" fill="#c27840" opacity=".16"/><path d="M493 518V224" stroke="#246fa9" stroke-width="2.5" stroke-dasharray="7 7" marker-end="url(#blue-arrow)"/><path d="M674 314L550 216" stroke="#b66027" stroke-width="2.5" stroke-dasharray="7 7" marker-end="url(#orange-arrow)"/>
<rect x="346" y="365" width="288" height="63" rx="8" fill="#f9f7ef" stroke="#a7c2d5"/><text id="fp-main" x="490" y="391" class="fp-label" fill="#246fa9">01 / PRINCIPAL</text><text x="490" y="413" class="fp-small">Vista entre las columnas</text>
<text id="fp-secondary" x="781" y="300" class="fp-label" fill="#b66027">02 / CERCANA</text></g>
<g fill="#152f3b" stroke="#f9f7ef" stroke-width="5"><circle cx="389" cy="330" r="20"/><circle cx="639" cy="330" r="20"/></g>
<path d="M370 337L311 350H250 M650 346L705 365H760" fill="none" stroke="#697579" stroke-width="1.5"/><text x="248" y="374" class="fp-small">Columna*</text><text x="759" y="388" class="fp-small">Columna*</text>
<path d="M810 555V367H965" fill="#e5e9e8" stroke="#687e82" stroke-width="2"/><text x="888" y="399" class="fp-label">OPERACIÓN</text><rect x="828" y="419" width="75" height="42" rx="4" fill="#152f3b"/><path d="M840 429H891M840 439H891M840 449H891" stroke="#a7b9bb" stroke-width="2"/><text x="865" y="482" class="fp-small">Consola</text><rect x="833" y="502" width="61" height="29" rx="3" fill="#f9f7ef" stroke="#152f3b" stroke-width="2"/><path d="M827 535H900" stroke="#152f3b" stroke-width="3"/><text x="932" y="523" class="fp-label">PC</text>
<g class="plan-cables"><path d="M500 546H950V531H901" stroke="#246fa9" stroke-width="5" fill="none" stroke-dasharray="12 6"/><path d="M704 331H948V509H903" stroke="#b66027" stroke-width="5" fill="none" stroke-dasharray="5 5"/><path d="M852 462V501" stroke="#327b67" stroke-width="5" fill="none"/><rect x="356" y="362" width="322" height="92" rx="8" fill="#f9f7ef" stroke="#bbc7c7"/><text x="517" y="391" class="fp-label">CABLES POR EL PERÍMETRO</text><text x="517" y="416" class="fp-small">2 USB activos de 10 m → PC junto a consola</text><text x="517" y="440" class="fp-small">Recorrido definitivo a medir</text></g>
<g transform="translate(493 541)"><circle r="25" fill="#246fa9" stroke="#f9f7ef" stroke-width="4"/><rect x="-12" y="-8" width="18" height="16" rx="3" fill="white"/><path d="M7 -5L15 -10V10L7 5Z" fill="white"/></g><text x="493" y="598" class="fp-label" fill="#246fa9">CÁMARA 01</text><text x="493" y="620" class="fp-small">Fija en pared, frente al escenario</text>
<g transform="translate(684 331)"><circle r="25" fill="#b66027" stroke="#f9f7ef" stroke-width="4"/><rect x="-12" y="-8" width="18" height="16" rx="3" fill="white"/><path d="M7 -5L15 -10V10L7 5Z" fill="white"/></g>
<path d="M210 555V523M300 555V523" stroke="#697579" stroke-width="1.5"/><text x="252" y="594" class="fp-small">Acceso*</text><path d="M965 185H935M965 250H935" stroke="#697579" stroke-width="1.5"/><text x="993" y="220" class="fp-small" transform="rotate(90 993 220)">Acceso*</text>
<text x="217" y="422" class="fp-label">PÚBLICO</text><text x="217" y="447" class="fp-small">Área libre</text><text x="217" y="468" class="fp-small">de trípodes</text><text x="550" y="55" class="fp-small">PARED DEL ESCENARIO · ORIENTACIÓN PROPUESTA: 10 m</text><text x="550" y="664" class="fp-small">Orientación y posiciones a confirmar en la visita · Sin escala</text></svg></div>
<div class="plan-legend" id="plan-legend"><span><i style="--key:#246fa9"></i>01 · Encuadre principal</span><span><i style="--key:#b66027"></i>02 · Detalle cercano</span><span>Las áreas de color indican intención de encuadre.</span></div></div>
<p class="plan-reading" id="plan-reading">01 · Escenario. 02 · Músico o instrumento, a unos 1–2 m. Los encuadres finales se eligen en el salón, según la banda, las columnas y la altura del público.</p>
<p class="plan-caption">Esquema sin escala para una sala de 6 × 10 m y escenario aproximado de 4 × 2 m. La orientación, las distancias, los accesos y la posición de las columnas se confirman en la visita.</p>
<details class="technical optics-details" id="encuadre"><summary>Explorar el encuadre de las cámaras <span>+</span></summary>
<section class="optics-note"><h3>Más distancia, más escenario en imagen.</h3><p id="optics-intro"></p><div class="optics-layout"><div><svg id="optics-svg" viewBox="0 0 620 650" role="img" aria-labelledby="opt-title opt-desc"><title id="opt-title">Campo visual teórico de la cámara seleccionada</title><desc id="opt-desc">Simulación del ancho captado sobre un escenario de cuatro metros de frente, según la distancia elegida. Sin columnas ni inclinación.</desc><rect width="620" height="650" fill="#f9f7ef"/><rect x="200" y="120" width="220" height="110" fill="#ead8c2" stroke="#997752" stroke-width="2"/><text x="310" y="146" text-anchor="middle">ESCENARIO · 4 × 2 m aprox.</text><path id="opt-cone" fill="#246fa9" fill-opacity=".15" stroke="#246fa9" stroke-width="2"/><path d="M200 92H420M200 84V100M420 84V100" stroke="#173443"/><text x="310" y="76" text-anchor="middle">4 m de frente</text><path id="opt-width-line" stroke="#246fa9" stroke-width="5"/><text id="opt-width-label" x="310" y="263" text-anchor="middle" fill="#246fa9"></text><g id="opt-camera"><circle r="18" fill="#246fa9"/><path d="M-9 -6H4V6H-9Z M5 -4L12 -8V8L5 4Z" fill="white"/></g><text id="opt-distance-label" x="310" text-anchor="middle"></text><text x="310" y="617" text-anchor="middle" font-size="13">Geometría ideal · sin columnas, inclinación ni zoom</text></svg></div><div><label class="distance-label" for="optics-camera">Comparar el lente</label><select id="optics-camera"><option value="redragon">Redragon Hitman · 72° diagonal</option><option value="c920">Logitech C920 · 78° diagonal</option><option value="brio">Logitech Brio · ajuste 90° diagonal</option></select><label class="distance-label" for="camera-distance">Distancia de la cámara al borde: <strong id="distance-output">4 m</strong></label><input id="camera-distance" type="range" min="1" max="4" value="4" step="0.1" aria-describedby="optics-result"><p class="optics-result" id="optics-result" aria-live="polite"></p><p class="small">El cálculo muestra el ancho visible a la altura del borde del escenario. La posición de los músicos y las columnas también influyen en la toma.</p></div></div><p class="small">Modelo geométrico para imagen 16:9, sin obstáculos ni inclinación. <a id="optics-source" href="https://www.logitech.com/es-es/shop/p/c920-pro-hd-webcam" target="_blank" rel="noopener noreferrer">Ficha del fabricante ↗</a></p></section></details>`;
document.getElementById('venue-plan').append(floorplan);
document.querySelectorAll('[data-plan]').forEach(button=>button.addEventListener('click',()=>{const cables=button.dataset.plan==='cables';document.querySelector('.plan-sheet').dataset.layer=button.dataset.plan;document.querySelectorAll('[data-plan]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#plan-legend').innerHTML=cables?'<span><i style="--key:#246fa9"></i>USB activo 10 m · Principal</span><span><i style="--key:#b66027"></i>USB activo 10 m · Cercana</span><span><i style="--key:#327b67"></i>Audio · Consola → PC</span>':'<span><i style="--key:#246fa9"></i>01 · Encuadre principal</span><span><i style="--key:#b66027"></i>02 · Detalle cercano</span><span>Las áreas de color indican intención de encuadre.</span>';document.querySelector('#plan-reading').textContent=cables?'Cada cámara llega a la PC con una extensión USB activa de 10 m. El recorrido por pared o techo mantiene libres los pasos. La consola aporta el audio; la conexión se define según sus salidas.':'01 · Escenario. 02 · Músico o instrumento, a unos 1–2 m. Los encuadres finales se eligen en el salón, según la banda, las columnas y la altura del público.'}));



const distanceInput=document.getElementById('camera-distance');
const cameraSelect=document.getElementById('optics-camera');
const diagonalToHorizontal=degrees=>2*Math.atan(Math.tan(degrees*Math.PI/360)*16/Math.sqrt(337));
const opticalModels={
 redragon:{name:'Redragon Hitman',short:'HITMAN',hfov:diagonalToHorizontal(72),angle:'72° diagonales; aproximadamente 64,7° horizontales',url:'https://www.redragon.com.br/hitman'},
 c920:{name:'Logitech C920',short:'C920',hfov:diagonalToHorizontal(78),angle:'78° diagonales; aproximadamente 70,4° horizontales',url:'https://www.logitech.com/es-es/shop/p/c920-pro-hd-webcam'},
 brio:{name:'Logitech Brio 4K',short:'BRIO',hfov:82.1*Math.PI/180,angle:'ajuste de 90° diagonales; 82,1° horizontales según Logitech',url:'https://hub.sync.logitech.com/brio'}
};
const numberES=n=>n.toLocaleString('es-AR',{maximumFractionDigits:2});
function renderOptics(){
 const model=opticalModels[cameraSelect.value],d=Number(distanceInput.value),factor=2*Math.tan(model.hfov/2),width=factor*d;
 const y=230+55*d,farHalf=factor*(d+2)*27.5,edgeHalf=width*27.5;
 document.getElementById('opt-cone').setAttribute('d',`M310 ${y}L${310-farHalf} 120H${310+farHalf}Z`);
 document.getElementById('opt-width-line').setAttribute('d',`M${310-edgeHalf} 230H${310+edgeHalf}`);
 document.getElementById('opt-width-label').textContent='En el borde: '+numberES(width)+' m';
 document.getElementById('opt-camera').setAttribute('transform',`translate(310 ${y})`);
 const label=document.getElementById('opt-distance-label');label.setAttribute('y',y+42);label.textContent=model.short+' · A '+numberES(d)+' m DEL BORDE';
 document.getElementById('distance-output').textContent=numberES(d)+' m';
 document.getElementById('optics-intro').textContent=model.name+' · '+model.angle+'. Distancia mínima teórica para abarcar 4 m de frente: '+numberES(4/factor)+' m, antes de dejar margen de encuadre.';
 document.getElementById('optics-source').href=model.url;
 document.getElementById('optics-result').textContent=width>=4?'El frente de 4 m entra en el campo teórico. Las columnas y el margen del encuadre se revisan en el lugar.':'Entran '+numberES(width)+' m de los 4 m del frente: no alcanza para un general completo en el borde.';
}
function syncPlanOptics(plan){
 cameraSelect.value=plan.main;
 document.getElementById('fp-main').textContent='01 / '+opticalModels[plan.main].short+' · PRINCIPAL';
 document.getElementById('fp-secondary').textContent='02 / '+(plan.secondary==='gadnic'?'GADNIC':'C920')+' · CERCANA';
 renderOptics();
}
distanceInput.addEventListener('input',renderOptics);cameraSelect.addEventListener('change',renderOptics);
window.addEventListener('keuken:plan',event=>syncPlanOptics(event.detail));
syncPlanOptics(window.keukenPlan||{main:'c920',secondary:'gadnic'});
