(() => {
const section=document.createElement('details');section.id='montaje';section.className='technical mounting-section';
section.innerHTML=`<summary>Soportes y montaje permanente <span>+</span></summary><p class="mount-intro">Cada cámara lleva una base y una rótula para ajustar y fijar la toma. Los dos conjuntos suman <strong>$43.966</strong> y están incluidos en las tres opciones. Los anclajes y las adaptaciones se cotizan según el apoyo elegido.</p>
<div class="mount-chain"><article><span>01 / FIJAR</span><img src="assets/base.webp" alt="Base de pared Genki" loading="lazy"><h3>Base de pared</h3><p>Genki · $13.993</p><small>Se atornilla sobre un apoyo firme y plano.</small></article><article><span>02 / ORIENTAR</span><img src="assets/rotula.webp" alt="Rótula Genki con bloqueo de orientación" loading="lazy"><h3>Rótula orientable</h3><p>Genki · $7.990</p><small>Permite girar, inclinar y bloquear la cámara.</small></article><article><span>03 / ENCUADRAR</span><img src="assets/c920.webp" alt="Cámara Logitech C920" loading="lazy"><h3>La cámara en su lugar</h3><p>Unión de 1/4″</p><small>Altura y posición elegidas con una prueba de imagen en el salón.</small></article></div>
<div class="mount-compat"><article><h3>C920 y Brio</h3><p>Montaje de trípode de 1/4″ documentado. Se confirma el punto de fijación y el ángulo durante la visita.</p></article><article><h3>Hitman</h3><p>El fabricante indica soporte para trípode. La medida de rosca requiere confirmación.</p></article><article><h3>Gadnic</h3><p>El montaje roscado no está confirmado. Puede requerir un adaptador específico o una cámara alternativa.</p></article></div>
<p class="mount-note">Las columnas de madera requieren un apoyo adecuado. Si la toma necesita separar la cámara de la pared o columna, se cotiza un brazo adicional. El montaje debe conservar libres los accesos y proteger el equipo de vibraciones y tirones.</p>
<div class="source-links"><a href="https://secure.logitech.com/assets/45920/hd-pro-webcam-c920-quick-start-guide.pdf" target="_blank" rel="noopener noreferrer">Montaje C920 ↗</a><a href="https://hub.sync.logitech.com/brio" target="_blank" rel="noopener noreferrer">Brio ↗</a><a href="https://www.redragon.com.br/hitman" target="_blank" rel="noopener noreferrer">Hitman ↗</a><a href="https://www.gadnic.com.ar/descargas/CAMWEB11.pdf" target="_blank" rel="noopener noreferrer">Gadnic ↗</a></div>`;
document.getElementById('venue-plan').after(section);
const sheet=document.querySelector('.plan-sheet');
const overview=document.createElement('div');overview.className='mobile-plan';overview.innerHTML=`<svg viewBox="0 0 360 330" role="img" aria-labelledby="mobile-plan-title"><title id="mobile-plan-title">Resumen del plano: escenario arriba, columnas centrales, cámara uno al frente y cámara dos cerca. Consola a la derecha. Esquema sin escala.</title><rect x="18" y="34" width="324" height="240" rx="3" fill="#f9f7ef" stroke="#173443" stroke-width="3"/><path d="M99 35H251L239 100Q180 140 111 100Z" fill="#ead8c2" stroke="#9b7b57"/><text x="176" y="67">ESCENARIO</text><text x="176" y="91" class="mobile-small">≈ 4 × 2 m</text><g class="plan-views"><path d="M163 250L137 95L210 95Z" fill="#246fa9" opacity=".18"/><path d="M260 157L181 85L230 105Z" fill="#b66027" opacity=".2"/></g><g class="plan-cables"><path d="M163 256H322V224" fill="none" stroke="#246fa9" stroke-width="4" stroke-dasharray="7 4"/><path d="M265 156H324V219" fill="none" stroke="#b66027" stroke-width="4" stroke-dasharray="4 3"/></g><circle cx="123" cy="143" r="11" fill="#173443"/><circle cx="227" cy="143" r="11" fill="#173443"/><text x="173" y="170" class="mobile-small">Columnas*</text><rect x="278" y="196" width="62" height="75" fill="#dfe5e4" stroke="#687e82"/><text x="309" y="225" class="mobile-small">PC</text><text x="309" y="245" class="mobile-small">Audio</text><circle cx="163" cy="253" r="14" fill="#246fa9"/><text x="163" y="259" fill="white">1</text><circle cx="264" cy="151" r="14" fill="#b66027"/><text x="264" y="157" fill="white">2</text><text x="86" y="213" class="mobile-small">Público</text><text x="180" y="304" class="mobile-small">Sala 6 × 10 m · orientación propuesta</text></svg><p><b>1</b> Frente al escenario · <b>2</b> Detalle cercano<br><span>*Posición de columnas por medir. Sin escala.</span></p></div>`;
sheet.querySelector('.plan-scroll').before(overview);
const open=document.createElement('button');open.className='plan-enlarge';open.textContent='Ampliar plano';open.type='button';sheet.querySelector('.plan-legend').before(open);
const dialog=document.createElement('dialog');dialog.className='plan-dialog';dialog.setAttribute('aria-labelledby','plan-dialog-title');dialog.innerHTML='<header><strong id="plan-dialog-title">Plano de Keuken · sin escala</strong><button type="button">Cerrar ×</button></header><p>Deslizá dentro del plano para recorrerlo.</p><div class="plan-dialog-body plan-sheet"></div>';document.body.append(dialog);
open.addEventListener('click',()=>{const svg=sheet.querySelector('.architect-plan').cloneNode(true);const mapping=new Map();svg.querySelectorAll('[id]').forEach(e=>{mapping.set(e.id,'zoom-'+e.id);e.id='zoom-'+e.id;});svg.querySelectorAll('*').forEach(e=>{for(const a of [...e.attributes]){let v=a.value;if(a.name==='aria-labelledby')v=v.split(' ').map(id=>mapping.get(id)||id).join(' ');else for(const [id,to]of mapping)v=v.replaceAll('url(#'+id+')','url(#'+to+')');if(v!==a.value)e.setAttribute(a.name,v);}});svg.setAttribute('aria-labelledby','zoom-fp-title zoom-fp-desc');const body=dialog.querySelector('.plan-dialog-body');body.replaceChildren(svg);body.dataset.layer=sheet.dataset.layer;dialog.showModal();body.scrollLeft=(body.scrollWidth-body.clientWidth)/2;});
dialog.querySelector('button').addEventListener('click',()=>dialog.close());
})();
