(() => {
const section=document.createElement('section');section.id='montaje';section.className='section mounting-section';
section.innerHTML=`<p class="eyebrow">MONTAJE / EL SOPORTE DEFINE LA TOMA</p><div class="section-heading"><h2>Fijar. Orientar.<br>Que no se mueva.</h2><p>Para este salón necesitamos un punto firme, una rótula que permita inclinar y girar, y una unión compatible con la cámara. Elegir dónde se ve al músico es el primer paso.</p></div>
<div class="mount-verdict"><strong>Corrección: el GL-105 no resolvía el montaje completo.</strong><p>Era una base para cámaras de seguridad, sin la unión y orientación necesarias para estas webcams. Se retiró de las listas. Ahora se prevé una base Genki más una rótula por cámara: <b>$21.983 por conjunto; $43.966 por los dos.</b> Anclajes, retención y cualquier adaptación se cotizan aparte.</p></div>
<div class="mount-chain"><article><span>01 / FIJACIÓN</span><img src="assets/base.webp" alt="Base Genki WALLSC-M con orificios de fijación y tornillo macho" loading="lazy"><h3>Base sobre apoyo firme</h3><p>WALLSC-M · $13.993</p><small>Sale con rosca macho 1/4″-20. Se fija con tornillos adecuados al apoyo; no abraza una columna redonda.</small></article><article><span>02 / ORIENTACIÓN</span><img src="assets/rotula.webp" alt="Rótula Genki con esfera y perilla para bloquear el ángulo" loading="lazy"><h3>Rótula con bloqueo</h3><p>Cabezal Genki · $7.990</p><small>La hembra de abajo recibe la base. El macho de arriba recibe la cámara. Girar, inclinar y bloquear la toma.</small></article><article><span>03 / COMPATIBILIDAD</span><img src="assets/c920.webp" alt="Logitech C920, modelo con montaje de trípode documentado" loading="lazy"><h3>Rosca real en la cámara</h3><p>No alcanza con un clip de monitor</p><small>Comprobar la rosca y que el cuerpo permita el ángulo requerido. Asegurar el cable para que no tire de la cámara.</small></article></div>
<div class="mount-compat"><article><span class="mount-badge">CONEXIÓN DOCUMENTADA</span><h3>C920 y Brio 4K</h3><p>Las Logitech elegidas tienen montaje para trípode de 1/4″. Base y rótula son compatibles por conexión. Aún hay que comprobar anclaje, inclinación útil, vibración y encuadre en el salón.</p></article><article><span class="mount-badge pending">MEDIDA A CONFIRMAR</span><h3>Redragon Hitman</h3><p>Redragon confirma soporte para trípode. La ficha consultada no especifica la medida de rosca: verificar 1/4″-20 y probar el conjunto antes de comprarlo.</p></article><article><span class="mount-badge pending">MONTAJE SIN RESOLVER</span><h3>Gadnic CAMWEB11</h3><p>Su ficha y manual no confirman una rosca. El kit es una previsión, no una compatibilidad demostrada. Hace falta comprobar la unidad, cotizar un adaptador rígido o cambiar la cámara. No dar por cerrado ese punto.</p></article></div>
<div class="mount-positions"><article><strong>Cámara 1 · frente al escenario</strong><p>Probar desde la pared opuesta, desplazándose hasta mirar entre las columnas. Montarla apenas por encima de las cabezas, según público sentado o de pie y altura de las vigas. Revisar caras, instrumentos y horizonte antes de fijar.</p></article><article><strong>Cámara 2 · detalle cercano</strong><p>Ensayar cerca de la tarima, a unos 1–2 m del músico. La base corta no permite rodear una columna. Si hace falta alejar la cámara del apoyo, medir ese desplazamiento y cotizar un brazo rígido con bloqueo; no está incluido.</p></article></div>
<p class="mount-note">En los troncos del salón no se puede asumir que una base plana asiente bien o que una pinza de escritorio alcance. Definir apoyo, permiso de fijación y anclaje antes de comprar. La selección del soporte se termina probando la toma con las luces y el público reales.</p>
<p class="mount-sources"><a href="https://secure.logitech.com/assets/45920/hd-pro-webcam-c920-quick-start-guide.pdf" target="_blank" rel="noopener noreferrer">Montaje C920 · Logitech ↗</a><a href="https://hub.sync.logitech.com/brio" target="_blank" rel="noopener noreferrer">Brio · Logitech ↗</a><a href="https://www.redragon.com.br/hitman" target="_blank" rel="noopener noreferrer">Hitman · Redragon ↗</a><a href="https://www.gadnic.com.ar/descargas/CAMWEB11.pdf" target="_blank" rel="noopener noreferrer">Manual Gadnic ↗</a></p>`;
document.getElementById('equipo').before(section);
const sheet=document.querySelector('.plan-sheet');
const overview=document.createElement('div');overview.className='mobile-plan';overview.innerHTML=`<svg viewBox="0 0 360 330" role="img" aria-labelledby="mobile-plan-title"><title id="mobile-plan-title">Resumen del plano: escenario arriba, columnas centrales, cámara uno al frente y cámara dos cerca. Consola a la derecha. Esquema sin escala.</title><rect x="18" y="34" width="324" height="240" rx="3" fill="#f9f7ef" stroke="#173443" stroke-width="3"/><path d="M99 35H251L239 100Q180 140 111 100Z" fill="#ead8c2" stroke="#9b7b57"/><text x="176" y="67">ESCENARIO</text><text x="176" y="91" class="mobile-small">≈ 4 × 2 m</text><g class="plan-views"><path d="M163 250L137 95L210 95Z" fill="#246fa9" opacity=".18"/><path d="M260 157L181 85L230 105Z" fill="#b66027" opacity=".2"/></g><g class="plan-cables"><path d="M163 256H322V224" fill="none" stroke="#246fa9" stroke-width="4" stroke-dasharray="7 4"/><path d="M265 156H324V219" fill="none" stroke="#b66027" stroke-width="4" stroke-dasharray="4 3"/></g><circle cx="123" cy="143" r="11" fill="#173443"/><circle cx="227" cy="143" r="11" fill="#173443"/><text x="173" y="170" class="mobile-small">Columnas*</text><rect x="278" y="196" width="62" height="75" fill="#dfe5e4" stroke="#687e82"/><text x="309" y="225" class="mobile-small">PC</text><text x="309" y="245" class="mobile-small">Audio</text><circle cx="163" cy="253" r="14" fill="#246fa9"/><text x="163" y="259" fill="white">1</text><circle cx="264" cy="151" r="14" fill="#b66027"/><text x="264" y="157" fill="white">2</text><text x="86" y="213" class="mobile-small">Público</text><text x="180" y="304" class="mobile-small">Sala 6 × 10 m · orientación propuesta</text></svg><p><b>1</b> Frente al escenario · <b>2</b> Detalle cercano<br><span>*Posición de columnas por medir. Sin escala.</span></p></div>`;
sheet.querySelector('.plan-scroll').before(overview);
const open=document.createElement('button');open.className='plan-enlarge';open.textContent='Ampliar plano y ver detalles';open.type='button';sheet.querySelector('.plan-legend').before(open);
const dialog=document.createElement('dialog');dialog.className='plan-dialog';dialog.setAttribute('aria-labelledby','plan-dialog-title');dialog.innerHTML='<header><strong id="plan-dialog-title">Plano de Keuken · sin escala</strong><button type="button">Cerrar ×</button></header><p>Deslizá dentro del plano para recorrerlo.</p><div class="plan-dialog-body plan-sheet"></div>';document.body.append(dialog);
open.addEventListener('click',()=>{const svg=sheet.querySelector('.architect-plan').cloneNode(true);const mapping=new Map();svg.querySelectorAll('[id]').forEach(e=>{mapping.set(e.id,'zoom-'+e.id);e.id='zoom-'+e.id;});svg.querySelectorAll('*').forEach(e=>{for(const a of [...e.attributes]){let v=a.value;if(a.name==='aria-labelledby')v=v.split(' ').map(id=>mapping.get(id)||id).join(' ');else for(const [id,to]of mapping)v=v.replaceAll('url(#'+id+')','url(#'+to+')');if(v!==a.value)e.setAttribute(a.name,v);}});svg.setAttribute('aria-labelledby','zoom-fp-title zoom-fp-desc');const body=dialog.querySelector('.plan-dialog-body');body.replaceChildren(svg);body.dataset.layer=sheet.dataset.layer;dialog.showModal();body.scrollLeft=(body.scrollWidth-body.clientWidth)/2;});
dialog.querySelector('button').addEventListener('click',()=>dialog.close());
})();
